### ISSUE TITLE
tutorial_tools.ipynb runs into keyError 'Dejavu Sans'

### ISSUE THREAD

**Issue by shirishr** [apahl/rdkit_ipynb_tools#2]
This is probably a known error for many who have been using rdkit.
My environment is ubuntu 16.04, python 3.6

Error occurs at 

mol_list[:5]

the full trace is:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/Downloads/rdkit_ipynb_tools/rdkit_ipynb_tools/tools.py in _repr_html_(self)
    274     def _repr_html_(self):
    275         id_prop = guess_id_prop(list_fields(self)) if self.ia else None
--> 276         return mol_table(self, id_prop=id_prop, order=self.order)
    277 
    278 

~/Downloads/rdkit_ipynb_tools/rdkit_ipynb_tools/tools.py in mol_table(sdf_list, id_prop, interact, highlight, show_hidden, order, img_dir, size)
   2127         else:
   2128             if img_dir is None:  # embed the images in the doc
-> 2129                 b64 = b64_img(mol, size * 2)
   2130                 img_src = "data:image/png;base64,{}".format(b64)
   2131 

~/Downloads/rdkit_ipynb_tools/rdkit_ipynb_tools/tools.py in b64_img(mol, size)
   2044 def b64_img(mol, size=300):
   2045     img_file = IO()
-> 2046     img = autocrop(Draw.MolToImage(mol, size=(size, size)))
   2047     img.save(img_file, format='PNG')
   2048 

~/anaconda3/envs/py36/lib/python3.6/site-packages/rdkit/Chem/Draw/__init__.py in MolToImage(mol, size, kekulize, wedgeBonds, fitImage, options, canvas, **kwargs)
    127     legend = ''
    128 
--> 129   drawer.AddMol(mol, **kwargs)
    130 
    131   if legend:

~/anaconda3/envs/py36/lib/python3.6/site-packages/rdkit/Chem/Draw/MolDrawing.py in AddMol(self, mol, centerIt, molTrans, drawingTrans, highlightAtoms, confId, flagCloseContactsDist, highlightMap, ignoreHs, highlightBonds, **kwargs)
    510         else:
    511           color = self.drawingOptions.elemDict.get(atom.GetAtomicNum(), (0, 0, 0))
--> 512         labelSize = self._drawLabel(symbol, pos, baseOffset, font, color=color, orientation=orient)
    513         labelSizes[atom.GetIdx()] = [labelSize, orient]
    514 

~/anaconda3/envs/py36/lib/python3.6/site-packages/rdkit/Chem/Draw/MolDrawing.py in _drawLabel(self, label, pos, baseOffset, font, color, **kwargs)
    322     x1 = pos[0]
    323     y1 = pos[1]
--> 324     labelSize = self.canvas.addCanvasText(label, (x1, y1, baseOffset), font, color, **kwargs)
    325     return labelSize
    326 

~/anaconda3/envs/py36/lib/python3.6/site-packages/rdkit/Chem/Draw/spingCanvas.py in addCanvasText(self, text, pos, font, color, **kwargs)
     58   def addCanvasText(self, text, pos, font, color=(0, 0, 0), **kwargs):
     59     text = re.sub(r'\<.+?\>', '', text)
---> 60     font = pid.Font(face=faceMap[font.face], size=font.size)
     61     txtWidth, txtHeight = self.canvas.stringBox(text, font)
     62     bw, bh = txtWidth + txtHeight * 0.4, txtHeight * 1.4

KeyError: 'Dejavu Sans'

Thank you in advance for suggested fix

Update:

I commented out the line **Draw.DrawingOptions.atomLabelFontFace = "DejaVu Sans"**

from

the **notebook** as well as **clustering.py, pipeline.py, sar.py, tools.py**

**Comment by shirishr** [comment]
See the update above.
With that the issue resolved itself.

**Comment by apahl** [comment]
Yes, these lines can be safely removed.  
Maybe I should put those into try / except blocks...
